
-- Drop unused existing tables
DROP TABLE IF EXISTS user_task;
DROP TABLE IF EXISTS user_badge;
DROP TABLE IF EXISTS `user`;


-- user
-- Change the user information.
-- user_id is generated by frontend as UUID / nickname-based UUID.
CREATE TABLE IF NOT EXISTS `user` (
    user_id VARCHAR(64) PRIMARY KEY COMMENT 'User UUID generated by frontend',
    nickname VARCHAR(100) NOT NULL COMMENT 'User display nickname',
    total_point INT NOT NULL DEFAULT 0 COMMENT 'User total award points',
    create_time TIMESTAMP NOT NULL COMMENT 'User first open the app'
);


-- park
-- Store park information and geographic location.
CREATE TABLE IF NOT EXISTS park (
    park_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    park_name VARCHAR(255) NOT NULL COMMENT 'Park name',
    `description` TEXT NOT NULL COMMENT 'Park description',
    latitude DECIMAL(10,7) NOT NULL COMMENT 'Park latitude',
    longitude DECIMAL(10,7) NOT NULL COMMENT 'Park longitude',
    st_point POINT NOT NULL SRID 4326 COMMENT 'Geographic point for spatial query'
);


-- story
-- Store AI-generated or predefined story for each park.
-- One park can have multiple stories.

CREATE TABLE IF NOT EXISTS story (
    story_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    park_id INT NOT NULL COMMENT 'Related park ID',
    `name` VARCHAR(255) NOT NULL COMMENT 'Story name',
    `content` TEXT NOT NULL COMMENT 'Story content',
    expected_duration_sec INT NOT NULL COMMENT 'Expected story duration in seconds',

    CONSTRAINT fk_story_park
        FOREIGN KEY (park_id)
        REFERENCES park(park_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- question
-- Store questions linked to a story.
-- One story can have multiple questions.
CREATE TABLE IF NOT EXISTS question (
    question_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    story_id INT NOT NULL COMMENT 'Related story ID',
    order_index INT NOT NULL COMMENT 'Question order index within the story',
    `description` TEXT NOT NULL COMMENT 'Question description',
    `context` TEXT NOT NULL COMMENT 'Question context or background',
    answer VARCHAR(255) NOT NULL COMMENT 'Correct answer',
    reward INT NOT NULL DEFAULT 0 COMMENT 'Reward points for answering the question',

    CONSTRAINT fk_question_story
        FOREIGN KEY (story_id)
        REFERENCES story(story_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) COMMENT='Store story-based questions';



-- analytics_event
-- Store user activity and analysis events.
-- This table records time-based behaviour for dashboard analysis.
CREATE TABLE IF NOT EXISTS analytics_event (
    event_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    user_id VARCHAR(64) NOT NULL COMMENT 'User UUID generated by frontend',

    park_arrival TIMESTAMP NULL COMMENT 'Time when user arrives at the park',
    park_leave TIMESTAMP NULL COMMENT 'Time when user leaves the park',
    out_door_times INT DEFAULT 0 COMMENT 'outdoor times from park arrival to leave',

    task_start TIMESTAMP NULL COMMENT 'Task start time',
    task_end TIMESTAMP NULL COMMENT 'Task end time',
    task_duration_sec INT DEFAULT 0 COMMENT 'Task duration in seconds',

    CONSTRAINT fk_analytics_user
        FOREIGN KEY (user_id)
        REFERENCES `user`(user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) COMMENT='Store user behaviour events for analytics';
