-- Active: 1776143899874@@tp35-kids.mysql.database.azure.com@3306@snaphunter

-- Drop unused existing tables
DROP TABLE IF EXISTS user_task;

DROP TABLE IF EXISTS user_badge;

DROP TABLE IF EXISTS `user`;

-- user
-- Change the user information.
-- user_id is generated by frontend as UUID / nickname-based UUID.
CREATE TABLE IF NOT EXISTS `user` (
    user_id VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'User UUID generated by frontend',
    nickname VARCHAR(100) NOT NULL COMMENT 'User display nickname',
    total_point INT NOT NULL DEFAULT 0 COMMENT 'User total award points',
    create_time TIMESTAMP NOT NULL COMMENT 'User first open the app'
);

-- park
-- Store park information and geographic location.
CREATE TABLE IF NOT EXISTS park (
    park_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    park_name VARCHAR(255) NOT NULL COMMENT 'Park name',
    `description` TEXT NOT NULL COMMENT 'Park description',
    latitude DECIMAL(10, 7) NOT NULL COMMENT 'Park latitude',
    longitude DECIMAL(10, 7) NOT NULL COMMENT 'Park longitude',
    st_point POINT NOT NULL SRID 4326 COMMENT 'Geographic point for spatial query'
);

-- story
-- Store AI-generated or predefined story for each park.
-- One park can have multiple stories.

CREATE TABLE IF NOT EXISTS story (
    story_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    park_id INT NOT NULL COMMENT 'Related park ID',
    `name` VARCHAR(255) NOT NULL COMMENT 'Story name',
    `content` TEXT NOT NULL COMMENT 'Story content',
    expected_duration_sec INT NOT NULL COMMENT 'Expected story duration in seconds',
    CONSTRAINT fk_story_park FOREIGN KEY (park_id) REFERENCES park (park_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- question
-- Store questions linked to a story.
-- One story can have multiple questions.
CREATE TABLE IF NOT EXISTS question (
    question_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    story_id INT NOT NULL COMMENT 'Related story ID',
    order_index INT NOT NULL COMMENT 'Question order index within the story',
    `description` TEXT NOT NULL COMMENT 'Question description',
    `context` TEXT NOT NULL COMMENT 'Question context or background',
    answer VARCHAR(255) NOT NULL COMMENT 'Correct answer',
    reward INT NOT NULL DEFAULT 0 COMMENT 'Reward points for answering the question',
    CONSTRAINT fk_question_story FOREIGN KEY (story_id) REFERENCES story (story_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- analytics_event
-- Store user activity and analysis events.
-- This table records time-based behaviour for dashboard analysis.
CREATE TABLE IF NOT EXISTS analytics_event (
    event_id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    user_id VARCHAR(64) NOT NULL COMMENT 'User UUID generated by frontend',
    park_arrival TIMESTAMP NULL COMMENT 'Time when user arrives at the park',
    park_leave TIMESTAMP NULL COMMENT 'Time when user leaves the park',
    out_door_times INT DEFAULT 0 COMMENT 'outdoor times from park arrival to leave',
    task_start TIMESTAMP NULL COMMENT 'Task start time',
    task_end TIMESTAMP NULL COMMENT 'Task end time',
    task_duration_sec INT DEFAULT 0 COMMENT 'Task duration in seconds',
    CONSTRAINT fk_analytics_user FOREIGN KEY (user_id) REFERENCES `user` (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- insert story data for fiztory garden park
INSERT INTO
    story (
        park_id,
        `name`,
        `content`,
        expected_duration_sec
    )
VALUES (
        36,
        'The Time Traveler''s Map',
        "Welcome, explorer! I am Ollie, and I have been watching over Fitzroy Gardens for a very long time. Today we are going on a Time Traveler''s Map adventure — three secrets are hidden in this park, and only YOU can find them. Are you ready? Let''s go!",
        3600
    );

-- insert question data for the fiztory garden story
INSERT INTO
    question (
        story_id,
        order_index,
        `description`,
        `context`,
        answer,
        reward
    )
VALUES (
        1,
        1,
        'This little cottage is over 270 years old and it sailed here all the way from England! Workers had to take it apart piece by piece. What do you think they did to every single brick before packing them into boxes? Did they paint them, number them, or throw them away?',
        'Walk toward the small stone cottage with ivy on its walls. It looks like it belongs in a fairy tale. Stand outside the front gate and look up at the roof.',
        'Accept: numbered, wrote numbers on them, labelled, marked them. Hint 1: If you had hundreds of bricks that all looked the same, how would you remember which one goes where on the other side of the world? Hint 2: Imagine the world''s biggest jigsaw puzzle. You would need to write something on every piece so you knew exactly where it belonged.',
        20
    );

INSERT INTO
    question (
        story_id,
        order_index,
        `description`,
        `context`,
        answer,
        reward
    )VALUES (
        1,
        2,
        'PART A — Scar Tree: You can see the Wurundjeri people carefully cut away a piece of bark from this tree long ago. What do you think they made with it? A canoe, a shelter, or a fire? PART B — Tiny Village after Part A is correct: This tiny village was made by a 77-year-old man in England as a thank-you gift to Melbourne — he built every single building by hand! How many little buildings can you count inside the fence?',
        'PART A nav: Walk toward the big open lawn. Look for a tall eucalyptus tree with a long dark scar on its trunk — like an old wound that never healed. Stand right in front of it. PART B nav: Now walk just a little further. Look for a tiny village behind a low fence — the little houses only come up to your knees!',
        'PART A — Accept: canoe, boat, vessel, water transport. Hint 1: Look at the shape of the scar — long, curved, hollow. Imagine sitting inside that shape on the water. Hint 2: The Yarra River is nearby. What could you build from one big curved piece of bark to cross the water? PART B — Accept: any number between 20 and 25. Then confirm real answer is about 23. Hint 1: Start at one end of the fence, work around. Count every rooftop — big and tiny both count. Hint 2: Find the little church with the steeple first, then count outward from there.',
        20
    );

INSERT INTO
    question (
        story_id,
        order_index,
        `description`,
        `context`,
        answer,
        reward
    )VALUES (
        1,
        3,
        'TYPE: play — no question asked. Deliver play_instruction, then wait silently. When child returns and says ANYTHING, mark complete. Play instruction: You have discovered so many secrets today — a cottage that crossed an ocean in numbered boxes, a 40,000-year-old canoe scar, and a tiny thank-you village from England! Now it is time to celebrate. Go play on the giraffe swing and the dinosaur slide for twenty minutes. Ollie will be watching from the trees. Come back and tell me which one was your favourite! Closing: You are a true Fitzroy Gardens explorer! You now know secrets that most people who walk through this park never find out. The Wurundjeri people were here first, a cottage crossed an ocean in pieces, and a kind old man built a tiny village as a thank-you. This park holds thousands of years of stories — and YOU know all of them.',
        'Head to the playground — look for the tall giraffe swing and the big dinosaur slide. You will definitely see them, they are hard to miss!',
        'Accept: anything. Any word the child says when they return counts as a correct answer. Do not quiz them.',
        20
    );
